### ISSUE TITLE
Strange event behavior on IE11

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/cgxp#1004]
I do not quite understand, but there is a strange mix up with the mouse event behavior on IE11

First, there are quite a lot of problems when using the measure tools for instance:

http://geomapfish-demo.camptocamp.net/1.6

The lines are not anymore drawn on real time. (you get the same when playing with the profile)

Furthermore, the tool management does not work anymore:

http://sitn.ne.ch/prepublication16/theme/main

Try to interrogate a WMS layer on then try to draw a measure line -> objects are still interrogated (while making a measure).

The strange thing is that it seems only to occur since version 1.6.2:

http://preprod.cartoriviera.ch/

@gnerred, on which version of CGXP are you with cartoriviera ?

**Comment by gnerred** [comment]
The URL you mention http://preprod.cartoriviera.ch/ is on 1.5. My 1.6.2 version is on http://preprodnew.cartoriviera.ch/

**Comment by kalbermattenm** [comment]
Oups... Then, you have the same problems... on IE11... Event mangement is completely broken...

**Comment by gnerred** [comment]
Youhouhou....! So it is not possible to migrate with this issue...

**Comment by kalbermattenm** [comment]
Yeah... right-clic is also completely broken... It triggers a left-clic WMS getFeatureInfo query...

It does not even send a raster query...

**Comment by rbovard** [comment]
Confirmed here, it's a blocker...

**Comment by ger-benjamin** [comment]
Seem appear only on IE10 (And IE 11 because it loads this page with the IE10 document mode but the problem does not exists with the real IE11 document mode).

**Comment by sbrunner** [comment]
@ger-benjamin tomorow i eill give you son additions informations ...

**Comment by rbovard** [comment]
For the record, the right click works fine in `1.5`

**Comment by ger-benjamin** [comment]
Currently, we don't understand why that works in ``1.5`` and not in ``1.6``.
We just know that IE10 contains more bugs (among-other in Ext) than IE9 and IE11. So, this workaround bypasses this issue : https://github.com/camptocamp/c2cgeoportal/pull/1602 (will be available in 1.6.3)

**Comment by sbrunner** [comment]
@kalbermattenm @gnerred Can you test https://github.com/camptocamp/c2cgeoportal/pull/1602/files, it i's working well (also the profile and the lidar) ?

**Comment by kalbermattenm** [comment]
This is really better... See http://sitn.ne.ch/prepublication16/theme/main

Thanks a lot !

**Comment by gnerred** [comment]
Unfortunatly I have no time to test, I will be out tomorrow and thirsday. But I have applied the changes on my 1.6 : http://preprodnew.cartoriviera.ch , if someone wants to test...
