### ISSUE TITLE
IE8 (maybe IE9...) - FTS "Expected identifier"

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/cgxp#1006]
On IE8, the browser indicates an error "Expected identifier" here: https://github.com/camptocamp/cgxp/blob/master/core/src/script/CGXP/plugins/FullTextSearch.js#L155

I tested it on IE8 because I do not have any IE9 or IE10 browser.

I also do not know if this has any impact on 8 < IE < 11....

**Comment by rbovard** [comment]
I wanted to reproduce this issue with IE8 but I cannot load the application with this version of IE (and I also don't have IE9)...

**Comment by kalbermattenm** [comment]
Yes... This is normal, because of https://github.com/camptocamp/cgxp/pull/1005

**Comment by rbovard** [comment]
Mmmh ok, I don't even take the courage to open debug tools with IE8 ^^
