### ISSUE TITLE
Print V2 UI

### ISSUE THREAD

**Issue by rbovard** [camptocamp/cgxp#1007]
Is it normal that with the same JS code, the print V2 UI is not the same between versions 1.5 and 1.6?

![image](https://cloud.githubusercontent.com/assets/4549666/9733860/05d16872-562f-11e5-9b54-bbcb2ee05054.png) ![image](https://cloud.githubusercontent.com/assets/4549666/9733908/6849b8ba-562f-11e5-8891-e48c84f6aace.png)

**Comment by sbrunner** [comment]
Yes, 
The layout is adapted for the print v3,
and with the print v3 the set of fields [Title, Comment, Include legend] can change with the template, then it should be before., it should be possible to disable the Include legend option.

**Comment by rbovard** [comment]
Mmm OK...

And the buttons?

**Comment by sbrunner** [comment]
... I didn't see that inversed ...

**Comment by rbovard** [comment]
Ok, thanks for the answer.

I understand that for v3 the fileds are defined with a template, but is it possible to have the same UI as in 1.5 with print v2 ?

* Fileds and buttons order
* Optionnal include legend

This way it won't destabilize users...

Thanks.

**Comment by ger-benjamin** [comment]
These buttons will be reordered with the 1.6.3 release.

**Comment by rbovard** [comment]
Thanks, fields too?

And that?

> it should be possible to disable the Include legend option.

**Comment by sbrunner** [comment]
The field can't be reordered...

**Comment by rbovard** [comment]
Seriously?!

And the optional checkbox for legend?

**Comment by sbrunner** [comment]
In the plugin config:
```
    additionalAttributes: [{
        name: "title",
        label: "Title",
        type: "String"
    }, {
        name: "comment",
        label: "Comment",
        type: "String",
        useTextArea: true
    }]
```
default is:
```
    additionalAttributes: [{
        name: "title",
        label: "Title",
        type: "String"
    }, {
        name: "comment",
        label: "Comment",
        type: "String",
        useTextArea: true
    }, {
        name: "legend",
        type: "LegendAttributeValue"
    }]
```

**Comment by sbrunner** [comment]
For the format field as explain in a previous comment, for the print v3 he should be at the first in the form.
Then the users will necessary have a changes one time, and for codding it's preferably that for booth version we put it at the same place.

All others points will be fixed, than is it OK that we close this ticket ?

**Comment by rbovard** [comment]
It's ok for me, the worst one was the buttons order ;)

**Comment by sbrunner** [comment]
Thanks @rbovard :-)

**Comment by rbovard** [comment]
A question about the checkbox for legend, I removed it from the form with your plugin config, but does it really ask a PDF without a legend?
