### ISSUE TITLE
Print autoFit doesn't behaves the same when panel is in accordion

### ISSUE THREAD

**Issue by pgiraud** [camptocamp/cgxp#1017]
When the print panel is put in accordion, the print frame may not appear in the map view when the panel is open when autoFit option is set to false.
When used within a button in a bar, the frame correctly appears in the map view when the panel is open and is then not changed automatically.

See https://github.com/camptocamp/bl_geoview/issues/37

**Comment by ochriste** [comment]
probably solve https://github.com/camptocamp/c2cgeoportal/issues/1570 (same issue)
