### ISSUE TITLE
QueryBuilder: spatial condition disappears when changing to themes

### ISSUE THREAD

**Issue by eleu** [camptocamp/cgxp#1037]
If you add a spatial condition to the **QueryBuilder**, the conditions geometry is displayed:
![querybuilder_spatial_condition_displayed](https://cloud.githubusercontent.com/assets/9248944/9931611/7c61fab4-5d3d-11e5-9ada-ac76b703937e.jpg)

If you change to the tab **themes** and go back to the **QueryBuilder**, the conditions geometry disappears although the query is stilll active.
![querybuilder_spatial_condition_disappeared](https://cloud.githubusercontent.com/assets/9248944/9931653/dc37257c-5d3d-11e5-8d2a-87854cb5aa84.jpg)

(from https://github.com/camptocamp/baselstadt_mapbs/issues/53)

**Comment by sbrunner** [comment]
Probably an layer order or visibility issue ...
