### ISSUE TITLE
Backport no data value option to profile plugin into 1.5

### ISSUE THREAD

**Issue by rbovard** [camptocamp/cgxp#1055]
Is it possible to backport #951 into `1.5` branch?

**Comment by sbrunner** [comment]
Done :-)

**Comment by rbovard** [comment]
Cool, thanks a lot!

**Comment by rbovard** [comment]
Hum, I just tested and there is a missing `;` here https://github.com/camptocamp/cgxp/blob/1.5/core/src/script/CGXP/plugins/Profile.js#L475

**Comment by rbovard** [comment]
There are other JS errors...

I think we also need to backport those two:
* https://github.com/camptocamp/cgxp/pull/942
* https://github.com/camptocamp/cgxp/pull/956

I'm sorry about that, I thought it was straightforward...

**Comment by sbrunner** [comment]
OK, just done :-)

**Comment by rbovard** [comment]
Thanks @sbrunner, no more JS errors :)

But I think there is an issue with the feature, see https://github.com/camptocamp/cgxp/pull/951#issuecomment-160554011
