### ISSUE TITLE
Time picker not visible in IE11

### ISSUE THREAD

**Issue by eleu** [camptocamp/cgxp#1056]
For example in the demo application, the time picker is not visible for IE 11:

http://geomapfish-demo.camptocamp.net/1.6/theme/OSM?map_x=542000&map_y=154000&map_zoom=7&tree_groups=Layers

![image](https://cloud.githubusercontent.com/assets/1632411/11439076/69230314-94f9-11e5-9e55-7db80b432bb0.png)

The time slider is well visible.

Maybe this is the same problem as before with the time slider, c.f. https://github.com/camptocamp/cgxp/issues/687

**Comment by ochriste** [comment]
mmm I cant reproduce the problem in the demo

**Comment by ochriste** [comment]
do you have another url?

**Comment by ochriste** [comment]
initialization problem: on first display, the timepicker container has a size of zero.
it display correctly if you close and open the tree again.
