### ISSUE TITLE
layers are not shown with permalink

### ISSUE THREAD

**Issue by adahinden** [camptocamp/cgxp#1063]
We find an issue in GMF 1.5 using a **comma** "," in a **layer-group name**. If this is the case, the layers are not shown on the map after calling the url from the permalink plugin.

Unfortunately I can't test this on GMF 1.6. Can someone reproduce it?

**Comment by sbrunner** [comment]
It's not possible to put a coma in the group name ..

**Comment by sbrunner** [comment]
It's used to separate the different groups in the permalink
