### ISSUE TITLE
Timeslider and default expanded groups

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/cgxp#1074]
We have a group, called "Mobilité", containing a layer with a timeslider :

![img1](https://cloud.githubusercontent.com/assets/1681332/12743350/acb44c3c-c98d-11e5-8f24-bdf3ef92add4.png)

When expanding this one by clicking on "Mobilité" and "Réseau routier", you get the result hereunder, note that group "Trafic Journalier Moyen" is expanded by default (configuration in admin panel), so I did not click on it to expand it:

![img2](https://cloud.githubusercontent.com/assets/1681332/12743354/b2defcf6-c98d-11e5-8289-a0a2ef5517b6.png)

The problem is that layer "Trafic 2002-2011" should show a timeslider...

Now if you collapse / expand again group "Trafic Journalier Moyen", then the timeslider is rendered (because of https://github.com/camptocamp/cgxp/blob/1.6/core/src/script/CGXP/widgets/tree/LayerTree.js#L442):

![img3](https://cloud.githubusercontent.com/assets/1681332/12743433/2a61c254-c98e-11e5-9865-9ab1687334b1.png)

![img4](https://cloud.githubusercontent.com/assets/1681332/12743437/2d87ee4a-c98e-11e5-8dd3-2b37302cc581.png)

I think there is some kind of a bug here... The timeslider should be rendered even if its containing group is expanded by default.

I tried to play a bit with the event defined on line <a href="https://github.com/camptocamp/cgxp/blob/1.6/core/src/script/CGXP/widgets/tree/LayerTree.js#L442" target=_blank>442</a>, but I could not find a way to resolve the bug...

Any hint ?

**Comment by sbrunner** [comment]
Is it possible to test it on a server?
On witch theme are you?

**Comment by kalbermattenm** [comment]
http://sitn.ne.ch/dev_internet16/wsgi/theme/routes

I created a group "test_expand" which shows you the issue...:
* First, expand "test_expand"
* The group expands, but the timeslider is not visible
* Collapse "Trafic Journalier Moyen" and expand it

-> timeslider appears...

**Comment by sbrunner** [comment]
On witch navigator / version?

**Comment by sbrunner** [comment]
I tested with Firefox and Chrome and it seam working ...

**Comment by kalbermattenm** [comment]
On Firefox 44, Chrome Version 48.0.2564.97 m

On Internet 11, the timeslider is even not rendered.... (something happens... but the timeslider is not viisble...)

And obviously on Windows 7....

FYI, do not activated the group / layer, just expand them using the little white/black arrows.

**Comment by sbrunner** [comment]
I read to fast, now I see it :-)

**Comment by kalbermattenm** [comment]
OK, cool ;-)

**Comment by sbrunner** [comment]
Does #1075 works well?

**Comment by kalbermattenm** [comment]
Yep, it does the job (even in IE11...) !

See http://sitn.ne.ch/dev_internet16/wsgi/theme/routes

**Comment by sbrunner** [comment]
Excellent :-), thanks!

**Comment by kalbermattenm** [comment]
Thank you @sbrunner ! ;-)
