### ISSUE TITLE
printing frame behavior

### ISSUE THREAD

**Issue by adahinden** [camptocamp/cgxp#1081]
If I do following config on the print plugin (viewer.js)

> autoFit: false

the print frame will not recenter and change his scale automatically. In some case this is a practical way, but of course you can easily lose the frame. To prevent loosing the frame with these settings, we were asked, if we could at least reset the print frame after closing and reopening the print register tab.

In my opinion this would be a good improvement. Is this already done in GMF 1.6?

**Comment by eleu** [comment]
Is the behaviour as seen in http://map.geo.bs.ch/ what you want? (this is 1.6.x)

**Comment by eleu** [comment]
If the print functionality is in the accordeon, it is never really closed.

But if it is as a button in the toolbar, it is open / closed and the behaviour is correct (I suppose it is also correct for the version 1.5.x).

**Comment by adahinden** [comment]
Yes, this is what we were looking for. I will test it on 1.5, thanks!
