### ISSUE TITLE
Permalinks broken with HTTPS

### ISSUE THREAD

**Issue by rbovard** [camptocamp/cgxp#1087]
If a non HTTPS permalink is opened on a HTTPS server, the permalink is broken (lines are gone, fill color is black, maybe more...).

To reproduce:
- https://geomapfish-demo.camptocamp.net/1.6
- Create a line and an area
- Generate a permalink http://geomapfish-demo.camptocamp.net/1.6/s/nQpv
- Open permalink to get full URL _(permalink is OK)_ https://geomapfish-demo.camptocamp.net/1.6/theme/Transport?map_x=542000&map_y=154000&map_zoom=3&rl_features=Fl(hnv3F1gkv_1k7Fgzu-~~strokeColor*%252399CC00%27strokeWidth*1)a(gz3Dh56_h9g-1bPh2h-zvQh3v*gta-heCzrNgm5F1mu-~~fillColor*%25233366FF%27strokeColor*%25233366FF%27strokeWidth*1)
- Replace `https` by `http` to simulate an old permalink without HTTPS http://geomapfish-demo.camptocamp.net/1.6/theme/Transport?map_x=542000&map_y=154000&map_zoom=3&rl_features=Fl(hnv3F1gkv_1k7Fgzu-~~strokeColor*%252399CC00%27strokeWidth*1)a(gz3Dh56_h9g-1bPh2h-zvQh3v*gta-heCzrNgm5F1mu-~~fillColor*%25233366FF%27strokeColor*%25233366FF%27strokeWidth*1)

The permalink is broken.

![image](https://cloud.githubusercontent.com/assets/4549666/13426185/28250f94-dfac-11e5-8849-edf23af81edb.png)

![image](https://cloud.githubusercontent.com/assets/4549666/13426191/381becec-dfac-11e5-8777-7a10d4592860.png)

It seems that some extra chars (`52`) are added with auto redirect to HTTPS.

```
OK: rl_features=Fl(hnv3F1gkv_1k7Fgzu-~~strokeColor*%252  399CC00%2  7strokeWidth*1)a(gz3Dh56_h9g-1bPh2h-zvQh3v*gta-heCzrNgm5F1mu-~~fillColor*%252  33366FF%2  7strokeColor*%252  33366FF%2  7strokeWidth*1)
KO: rl_features=Fl(hnv3F1gkv_1k7Fgzu-~~strokeColor*%25252399CC00%2527strokeWidth*1)a(gz3Dh56_h9g-1bPh2h-zvQh3v*gta-heCzrNgm5F1mu-~~fillColor*%2525233366FF%2527strokeColor*%2525233366FF%2527strokeWidth*1)
```

**Comment by sbrunner** [comment]
Is it solved ?
As I remember it's in the apache configuration ...

**Comment by rbovard** [comment]
It seems (I reproduced my steps and the permalink is now OK)

Don't forget to document that, I think people who switch to HTTPS may have this issue.
