### ISSUE TITLE
QueryBuilder unable to filter with "like" or "contains" and special characters

### ISSUE THREAD

**Issue by ger-benjamin** [camptocamp/cgxp#1124]
To reproduce this issue:
- Go on https://testgmf.sig.cloud.camptocamp.net/1.6
- login
- in the query builder, select the "bus_stop" layer
- add the filter "name" "contains" "Pierre-Fatio (rive)"
- Do the query

-> No result, expect 1

Set the filter to "name" "contains" "Pierre-Fatio \(rive\)"

- > 1 result: correct

We need to escape the value with OpenLayers.Filter.Comparison.LIKE
(-> in our interface, with "contains" and "like" operators)

**Comment by sbrunner** [comment]
Doesn't it also affect ngeo?

**Comment by ger-benjamin** [comment]
I still need to see that. It depends on how ol3 is made
