### ISSUE TITLE
Incorrect opacity slider behaviour for WMTS layers placed at the root of a theme

### ISSUE THREAD

**Issue by asaunier** [camptocamp/cgxp#423]
When a WMTS layer is not in a layergroup (directly at the root of a theme), the opacity slider of the WMTS layer is at "opacity: 100%" whereas the slider cursor is positioned at the left end of the slider (opacity: 0).

The problem was observed when dealing with #406.

**Comment by sbrunner** [comment]
A layer at the theme root raise an error in the version 1.6
