### ISSUE TITLE
Wrong support of maxFeatures in Mapserver

### ISSUE THREAD

**Issue by asaunier** [camptocamp/cgxp#783]
A few months ago I have reintroduced the use of the "maxFeatures" parameter to the WFS GetFeature requests:
https://github.com/camptocamp/cgxp/blob/master/core/src/script/CGXP/plugins/GetFeature.js#L523
(in the QueryBuilder as well I think).

Some strange results have been observed at BL (with Mapserver 6.5!) though: sometimes the query returns only features from a given layer, ignoring features from other layers that are also available, even though the max feature limit is apparently not reached.

A solution would be to remove the "maxFeatures" parameter from the WFS GetFeature requests. That means that we would still need to rely on the limitation done in mapserver proxy.

**Comment by asaunier** [comment]
I think this issue is no longer relevent and may be closed:
* ``maxFeatures`` is correctly taken into account in Mapserver 7
* we no longer have max features limit in mapserver proxy

**Comment by sbrunner** [comment]
OK, thanks @asaunier
