### ISSUE TITLE
WMTS layers with min/max resolutions and permalinks

### ISSUE THREAD

**Issue by rbovard** [camptocamp/cgxp#913]
When opening a permalink with a WMTS layer with min/max resolutions and outside the visibility range, the layer in the TOC is not grayed. If you zoom out and zoom in, then the layer is grayed, which is the expected behaviour.

Steps to reproduce:
* Create a WMTS layer with min/max resolutions
* Zoom in to be outside the visibility range -> the layer is grayed in the TOC -> __OK__
* Create a permalink and open it -> the layer is not grayed in the TOC -> __KO__
* Zoom out and in -> the layer is grayed in the TOC -> __OK__

PS: I'm not sure if it's a CGXP or C2Cgeoportal issue...

**Comment by rbovard** [comment]
@sbrunner Thanks a lot for the resolution of this one but is it possible to backport it in `1.5` branch since it's a bugfix?

**Comment by sbrunner** [comment]
Done :-)

**Comment by rbovard** [comment]
Cool, thanks !
