### ISSUE TITLE
MapFishPrintv3Provider - double slashes in URLs

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/cgxp#943]
This has more to do with GeoExt... but...

In the <a href="https://github.com/geoext/geoext/blob/master/lib/GeoExt/data/MapFishPrintv3Provider.js" target=_blank>MapFishPrintv3Provider</a>, all URLs are constructed using `this.url + "/the_url_to_call.js"`, see https://github.com/geoext/geoext/blob/master/lib/GeoExt/data/MapFishPrintv3Provider.js#L90 for example.

In the usual <a href="https://github.com/geoext/geoext/blob/master/lib/GeoExt/data/PrintProvider.js" target=_blank>PrintProvider</a>, they are constructed without the slash, something like `this.url + "the_url_to_call.js"`, see https://github.com/geoext/geoext/blob/master/lib/GeoExt/data/PrintProvider.js#L113 for example.

Using MapFishPrintv3Provider, makes URLs having double slashes, something like:

http://myserver.com/printproxy//capabilities.json?version=6a924099137c4feabbb6b9d73b6e2541

Which returns an error 500... (but it works if http:/myserver.com/printproxy/capabilities.json?version=6a924099137c4feabbb6b9d73b6e2541)

I could propose a PR in GeoExt to avoid that, but was that slash stuff done on any purpose ?

**Comment by kalbermattenm** [comment]
I still have this issue with 1.6.0rc1

**Comment by sbrunner** [comment]
Will be fixed with: https://github.com/geoext/geoext/pull/110
