### ISSUE TITLE
Chrome: Not possible to remember password anymore

### ISSUE THREAD

**Issue by eleu** [camptocamp/cgxp#952]
Similar to https://github.com/camptocamp/cgxp/issues/588, it is since some time not possible to remember the password in the browser, but this only for Chrome.

**Comment by pgiraud** [comment]
What I found is that the browser ask the user if he/she wants to save the password which is expected.
But the saved username and password are not used when trying to log in later.

**Comment by eleu** [comment]
is this solved? was it a Chrome bug?

**Comment by sbrunner** [comment]
It's a Chrome issue ...

**Comment by eleu** [comment]
ok thanks
