### ISSUE TITLE
Warning message and open login form with secured permalink

### ISSUE THREAD

**Issue by rbovard** [camptocamp/cgxp#955]
When opening a permalink with a private layer, the warning message and login form doesn't show up (the layer `sct_balayage` in layergroup `sct_voirie` is private).

http://map.nyon.ch/theme/espaces_publics?map_x=507000&map_y=137850&map_zoom=3&tree_group_layers_equipements_publics=te_mobilier_sacs%2Cte_mobilier_wc&tree_group_layers_mobilier_panneaux=&tree_group_layers_sct_voirie=sct_balayage

![image](https://cloud.githubusercontent.com/assets/4549666/7930180/76e16fc4-0906-11e5-8ce8-89043f1f10da.png)

It's very strange because if activate all layers in `equipements_publics`, the message show up...

http://map.nyon.ch/theme/espaces_publics?map_x=507000&map_y=137850&map_zoom=3&tree_group_layers_equipements_publics=te_mobilier_bancs%2Cte_mobilier_corbeilles_autre%2Cte_mobilier_corbeilles_esve%2Cte_mobilier_corbeilles_voirie%2Cte_mobilier_corbeilles_ecole%2Cte_mobilier_corbeilles_batiment%2Cte_mobilier_corbeilles_all%2Cte_mobilier_sacs%2Cte_mobilier_wc&tree_group_layers_mobilier_panneaux=&tree_group_layers_sct_voirie=sct_balayage

![image](https://cloud.githubusercontent.com/assets/4549666/7930188/83c37c28-0906-11e5-9f5c-2559125bec37.png)

![image](https://cloud.githubusercontent.com/assets/4549666/7930227/d3ce49dc-0906-11e5-8722-be6e5071bc5e.png)

It's related to #893

**Comment by rbovard** [comment]
@sbrunner Thanks a lot for the resolution of this one but is it possible to backport it in `1.5` branch since it's a bugfix?

**Comment by sbrunner** [comment]
Done :-)

**Comment by rbovard** [comment]
Cool, thanks !
